import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import '../services/api.dart';
import '../widgets/status_icons.dart';
class ProblemsScreen extends StatefulWidget{const ProblemsScreen({super.key});@override State<ProblemsScreen> createState()=>_ProblemsScreenState();}
class _ProblemsScreenState extends State<ProblemsScreen>{String filter='all';String? date;final search=TextEditingController();bool loading=true;String? error;List<dynamic> items=[];
@override void initState(){super.initState();load();} Future<void> load()async{setState(()=>loading=true);try{items=await Api.instance.problems(type:filter,date:date,search:search.text);error=null;}catch(e){error=e.toString();}if(mounted)setState(()=>loading=false);}
Future<void> pickDate()async{final d=await showDatePicker(context:context,firstDate:DateTime(2020),lastDate:DateTime.now(),initialDate:DateTime.now());if(d!=null){setState(()=>date=DateFormat('yyyy-MM-dd').format(d));load();}}
@override Widget build(BuildContext c){const fs=[('all','الكل'),('reclamation','الشكاوى'),('accident','الحوادث'),('vidange','Vidange')];return Column(children:[SingleChildScrollView(scrollDirection:Axis.horizontal,padding:const EdgeInsets.all(10),child:Row(children:fs.map((f)=>Padding(padding:const EdgeInsetsDirectional.only(end:6),child:ChoiceChip(label:Text(f.$2),selected:filter==f.$1,onSelected:(_){setState(()=>filter=f.$1);load();}))).toList())),Padding(padding:const EdgeInsets.symmetric(horizontal:12),child:Row(children:[Expanded(child:TextField(controller:search,onSubmitted:(_)=>load(),decoration:const InputDecoration(prefixIcon:Icon(Icons.search),hintText:'بحث',border:OutlineInputBorder()))),IconButton.filledTonal(onPressed:pickDate,icon:const Icon(Icons.calendar_month))])),if(date!=null)Text('التاريخ: '+date!),Expanded(child:loading?const Center(child:CircularProgressIndicator()):error!=null?Center(child:Text(error!)):ListView.separated(padding:const EdgeInsets.all(12),itemCount:items.length,separatorBuilder:(_,__)=>const SizedBox(height:5),itemBuilder:(_,i){final p=Map<String,dynamic>.from(items[i]);final a=p['problem_type']=='accident';return Card(child:ListTile(leading:Icon(a?Icons.warning_rounded:Icons.report_problem_outlined,color:a?const Color(0xFF7B3FF2):null),title:Text((p['vehicle']??'-').toString()+' • '+(p['driver_name']??'-').toString()),subtitle:Text((p['problem_text']??'').toString()+'\\n'+(p['date']??'').toString()),trailing:StatusIcons(icons:a?['accident']:[p['status']=='قيد التصليح'?'in_progress':'pending']),onTap:()=>showActions(p)));}))]);}
Future<void> showActions(Map<String,dynamic> p)async{final id=int.tryParse(p['id'].toString());if(id==null)return;showModalBottomSheet(context:context,builder:(_)=>Column(mainAxisSize:MainAxisSize.min,children:[ListTile(title:Text('مشكلة #'+id.toString())),if(p['problem_type']!='accident')ListTile(leading:const Icon(Icons.warning),title:const Text('تحويل إلى حادث'),onTap:()async{await Api.instance.convertAccident(id);if(mounted){Navigator.pop(context);load();}}),ListTile(leading:const Icon(Icons.check),title:const Text('تسجيل الإصلاح'),onTap:()async{await Api.instance.fixProblem(id);if(mounted){Navigator.pop(context);load();}})]));}}
